-- 20261009_02 — Client <-> studio chat on a booking
--
-- Run in the Supabase SQL Editor after 20261009_01_admin_roles.sql.
-- Safe to re-run.
--
-- Every message belongs to one booking. Clients may only read and write the
-- threads attached to their own bookings; studio accounts may read and write
-- every thread. That rule is enforced in api/chat.php, not in SQL, because
-- the PHP application owns authentication.
--
-- Optional environment variable: PHODIO_CHAT_KEY
--   When it is set, api/chat.php also accepts a per-booking HMAC token
--   (X-Phodio-Chat-Token). The token lets the chat survive a Vercel cold
--   start that loses the PHP session file. When it is not set, chat falls
--   back to the normal PHP session / phodio_session cookie only.

CREATE TABLE IF NOT EXISTS chat_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id   INTEGER NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    sender_type  VARCHAR(10) NOT NULL CHECK (sender_type IN ('client', 'admin')),
    sender_id    INTEGER,
    sender_name  VARCHAR(120) NOT NULL DEFAULT 'Studio',
    body         TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    read_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS chat_messages_booking_created_idx
    ON chat_messages (booking_id, created_at);

-- Partial index: cheap "unread" lookups.
CREATE INDEX IF NOT EXISTS chat_messages_unread_idx
    ON chat_messages (booking_id)
    WHERE read_at IS NULL;

-- The PHP application owns authentication and server-side authorization.
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
